# 아이템 A로 아이템 B를 만들면 A가 PARENT 아이템
# A -> B -> C가 있다면 A가 ROOT 아이템
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO AS I
WHERE ITEM_ID NOT IN (
    SELECT PARENT_ITEM_ID
    FROM ITEM_TREE
    HAVING PARENT_ITEM_ID IS NOT NULL
)
ORDER BY 1 DESC