SELECT ID, IFNULL(C.COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA AS D
LEFT JOIN (
    SELECT PARENT_ID, COUNT(PARENT_ID) AS COUNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
) AS C
ON D.ID = C.PARENT_ID
ORDER BY 1