# CAR_ID 14는 HISTORY 내역에 없음. 
SELECT C.CAR_ID, C.CAR_TYPE,
    ROUND(C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE/100), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV') AND
    H.CAR_ID NOT IN ( # HISTORY_ID가 아닌, CAR_ID를 제외해줘야 해당되는 CAR가 빠짐
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE DATE_FORMAT(END_DATE, '%Y-%m-%d') >= '2022-11-01'
    AND DATE_FORMAT(START_DATE, '%Y-%m-%d') <= '2022-11-30'
    )
    AND P.DURATION_TYPE = '30일 이상'
GROUP BY C.CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC
/*
SELECT *
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE DATE_FORMAT(END_DATE, '%Y-%m-%d') >= '2022-11-01'
    AND DATE_FORMAT(START_DATE, '%Y-%m-%d') <= '2022-11-30'
*/