SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE * 30 *(1-
        (
            SELECT DISCOUNT_RATE
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
            WHERE DURATION_TYPE = '30일 이상' AND CAR_TYPE = C.CAR_TYPE
        )/100
    )
) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C 
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H # CAR_ID는 있지만 빌린 내역(HISTORY_ID) 없는 자동차를 포함하기 위해
ON H.CAR_ID = C.CAR_ID                          # 해당 자동차는 해당 기간동안 대여 가능해 놓치지 않고 세어줘야 한다
WHERE C.CAR_TYPE IN ('세단', 'SUV') AND
    C.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
GROUP BY C.CAR_ID
HAVING 500000 <= FEE AND FEE < 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC