# START_DATE가 11월에 있고, END_DATE가 그 이후에 있는 경우 혹은
# START_DATE가 11월 이전, END_DATE가 그 이후에 있는 경우를 판별하지 못하는 문제 발생
/*
SELECT A.CAR_ID, A.CAR_TYPE, ROUND((30*A.DAILY_FEE) * (1-C.DISCOUNT_RATE/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
ON A.CAR_ID = B.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C
ON A.CAR_TYPE = C.CAR_TYPE           
WHERE (A.CAR_TYPE = '세단' OR A.CAR_TYPE = 'SUV') 
    AND (30*A.DAILY_FEE) >= 500000 AND (30*A.DAILY_FEE) < 2000000
    AND DATE_FORMAT(B.START_DATE, '%Y-%m') != '2022-11' AND DATE_FORMAT(B.END_DATE, '%Y-%m') != '2022-11'
    AND C.DURATION_TYPE = '30일 이상'
GROUP BY A.CAR_ID
ORDER BY A.CAR_TYPE, A.CAR_ID DESC
*/

SELECT 
    C.CAR_ID, 
    C.CAR_TYPE, 
    FLOOR(C.DAILY_FEE * 30 * (1 - DP.DISCOUNT_RATE / 100)) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR C
LEFT JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY RH 
    ON C.CAR_ID = RH.CAR_ID 
    AND RH.START_DATE <= '2022-11-30' 
    AND RH.END_DATE >= '2022-11-01'
JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP 
    ON C.CAR_TYPE = DP.CAR_TYPE 
    AND DP.DURATION_TYPE = '30일 이상'
WHERE 
    C.CAR_TYPE IN ('세단', 'SUV')
    AND RH.HISTORY_ID IS NULL  -- 2022년 11월 1일~30일 사이에 대여 이력이 없는 자동차만 선택
HAVING 
    FEE >= 500000 AND FEE < 2000000
ORDER BY 
    FEE DESC, 
    C.CAR_TYPE ASC, 
    C.CAR_ID DESC;