SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT FOOD_TYPE,
            REST_ID,
            REST_NAME,
            FAVORITES,
            MAX(FAVORITES) OVER(PARTITION BY FOOD_TYPE) MAX_FAVORITES
    FROM REST_INFO
)A
WHERE A.FAVORITES = A.MAX_FAVORITES
ORDER BY FOOD_TYPE DESC

/*
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC
*/