SELECT ID,
    CASE
        WHEN PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) > 0.75 THEN 'LOW'
        WHEN PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) > 0.5 THEN 'MEDIUM'
        WHEN PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) > 0.25 THEN 'HIGH'
        ELSE 'CRITICAL'
    END AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY 1