/*
SELECT H.HISTORY_ID,
    ROUND(
        C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE)+1) *
        (CASE
             WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 7 THEN 1-(P.DISCOUNT_RATE/100)
            WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 30 THEN 1-(P.DISCOUNT_RATE/100)
            WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 90 THEN 1-(P.DISCOUNT_RATE/100)
            ELSE 1
        END)
    ) AS FEE, P.DURATION_TYPE, P.DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
JOIN CAR_RENTAL_COMPANY_CAR AS C
ON H.CAR_ID = C.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC
*/

SELECT  B.HISTORY_ID
        ,ROUND(A.DAILY_FEE * (DATEDIFF(B.END_DATE,B.START_DATE) + 1) * (1- CASE WHEN DISCOUNT_RATE IS NULL THEN 0 ELSE DISCOUNT_RATE END/100)) AS FEE
  FROM  CAR_RENTAL_COMPANY_CAR A
  JOIN  CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    ON  A.CAR_ID = B.CAR_ID
  LEFT
  JOIN  CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
    ON  A.CAR_TYPE = C.CAR_TYPE
        AND CASE WHEN DATEDIFF(B.END_DATE,B.START_DATE) + 1 >= 90 THEN '90일 이상'
                 WHEN DATEDIFF(B.END_DATE,B.START_DATE) + 1 >= 30 THEN '30일 이상'
                 WHEN DATEDIFF(B.END_DATE,B.START_DATE) + 1 >= 7 THEN '7일 이상' END = C.DURATION_TYPE
 WHERE  A.CAR_TYPE = '트럭'
 ORDER
    BY  2 DESC, 1 DESC