SELECT H.HISTORY_ID,
    ROUND(C.DAILY_FEE * (1 - (CASE WHEN P.DURATION_TYPE IS NULL THEN 0
                       ELSE P.DISCOUNT_RATE/100 END))
    * (DATEDIFF(H.END_DATE, H.START_DATE)+1), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE AND
    CASE
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 7 THEN '7일 이상'
        ELSE NULL
    END = P.DURATION_TYPE
WHERE C.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC