# 재귀 쿼리
WITH RECURSIVE rc
AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1
    FROM rc
    WHERE HOUR<23
)
SELECT rc.HOUR, IFNULL(O.COUNT, 0) AS COUNT
FROM rc
LEFT JOIN 
(
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
) AS O
ON rc.HOUR = O.HOUR
ORDER BY 1


# SELECT rc.HOUR, COUNT(*)
# FROM rc
# LEFT JOIN ANIMAL_OUTS
# ON rc.HOUR = HOUR(DATETIME)
# GROUP BY rc.HOUR

/* 변수사용
SET @HOUR = -1;
SELECT @HOUR := @HOUR+1 AS HOUR,
    (
        SELECT COUNT(*)
        FROM ANIMAL_OUTS
        WHERE HOUR(DATETIME) = @HOUR
    ) AS COUNT
FROM ANIMAL_OUTS
WHERE @HOUR < 23
*/