WITH RECURSIVE rc 
AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1
    FROM rc
    WHERE HOUR < 23
)

SELECT rc.HOUR, IFNULL(TEMP.COUNT, 0) AS COUNT
FROM rc
LEFT JOIN (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(ANIMAL_ID) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
) AS TEMP
ON rc.HOUR = TEMP.HOUR
ORDER BY rc.HOUR
