SELECT E.EMP_NO, E.EMP_NAME, 
    CASE 
        WHEN AVG(G.SCORE) >= 96 THEN 'S'
        WHEN AVG(G.SCORE) >= 90 THEN 'A'
        WHEN AVG(G.SCORE) >= 80 THEN 'B'
        ELSE 'C'
    END GRADE,
    CASE 
        WHEN AVG(G.SCORE) >= 96 THEN E.SAL * 0.2
        WHEN AVG(G.SCORE) >= 90 THEN E.SAL * 0.15
        WHEN AVG(G.SCORE) >= 80 THEN E.SAL * 0.1
        ELSE E.SAL * 0
    END BONUS
FROM HR_EMPLOYEES E
JOIN HR_DEPARTMENT D
JOIN HR_GRADE G
ON E.DEPT_ID = D.DEPT_ID AND E.EMP_NO = G.EMP_NO
GROUP BY G.EMP_NO
ORDER BY E.EMP_NO