SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW RR
JOIN
(
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC
    LIMIT 1
) AS TEMP
ON RR.MEMBER_ID = TEMP.MEMBER_ID
JOIN MEMBER_PROFILE MP
ON RR.MEMBER_ID = MP.MEMBER_ID
ORDER BY 3, 2