SELECT P.MEMBER_NAME, A.REVIEW_TEXT, DATE_FORMAT(A.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW A
JOIN 
(
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC
    LIMIT 1
) B
ON A.MEMBER_ID = B.MEMBER_ID
JOIN MEMBER_PROFILE P
ON A.MEMBER_ID = P.MEMBER_ID
ORDER BY 3, 2