/*
대여 시작일이 8월 ~ 10월 사이가 아닌 데이터들이 존재한다면,
EX) 동일한 CAR_ID로 대여 시작일이 7월인 케이스가 한 건 이상 존재 + 8월 ~ 10월 사이 대여 케이스가 5건 이상
위와 같은 상황이라면, 메인 쿼리에 8월부터 10월 사이에 대한 WHERE 조건문이 없다면
COUNT(HISTORY_ID)의 집계값은 7월 케이스의 COUNT와 8월 ~ 10월 사이 케이스의 COUNT를 합한 값이 출력될 것이다.
즉, 출력되는 COUNT(HISTORY_ID)도 8월 ~ 10월 사이에 기간으로 제한을 둬야
문제의 조건에 맞게 8월 ~ 10월 사이에 대한 집계만 진행된다는 것을 알 수 있다.

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE '2022-08-01' <= DATE(START_DATE) AND '2022-10-31' >= DATE(START_DATE)
    AND
    CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-08-01' <= DATE(START_DATE) AND '2022-10-31' >= DATE(START_DATE)
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)
GROUP BY MONTH(START_DATE), CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH(START_DATE), CAR_ID DESC
*/

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m') >= '2022-08' AND DATE_FORMAT(START_DATE, '%Y-%m') <= '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)
GROUP BY MONTH(START_DATE), CAR_ID
HAVING MONTH >= 8 AND MONTH <= 10
ORDER BY MONTH(START_DATE), CAR_ID DESC

