SELECT CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM (
    SELECT CATEGORY, PRICE,
        MAX(PRICE) OVER(PARTITION BY CATEGORY) MAX_PRICE,
        PRODUCT_NAME
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
) A
WHERE A.PRICE = A.MAX_PRICE
ORDER BY MAX_PRICE DESC